######################## default configuration ####################
baseURL = "https://kohsei-san.b-hood.site/lp/"
title = "校正さん"
theme = "kohsei-san-landing-page"
languageName = "Ja"
languageCode = "ja-jp"
# post pagination
paginate = 3
# post excerpt
hasCJKLanguage = true
#summaryLength = 15
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-106651880-5" # example : UA-123-45

# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Blog"
URL = "blog/"
weight = 1

[[menu.main]]
name = "Contact"
URL = "https://twitter.com/hata6502"
weight = 2

[[menu.main]]
name = "FAQ"
URL = "https://github.com/hata6502/kohsei-san/discussions"
weight = 3

[[menu.main]]
name = "Sponsor"
URL = "https://github.com/sponsors/hata6502"
weight = 4

# footer menu middle
[[menu.footer_middle]]
name = "クイックスタート"
URL = "https://kohsei-san.b-hood.site/?text=%E5%86%97%E9%95%B7%E3%81%AA%E8%A1%A8%E7%8F%BE%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82%0A%0A%E8%AA%A4%E5%AD%97%E8%84%B1%E5%AD%97%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%97%E3%81%9F%E3%82%8A%E3%80%81%E8%A8%80%E3%81%84%E5%9B%9E%E3%81%97%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%97%E3%81%BE%E3%81%99%E3%80%82%0A%0A%E5%85%A5%E5%8A%9B%E3%83%9F%E3%82%B9%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%3A+%E5%85%A5%E5%8A%9Bm%E3%82%B9%0A%0A%E5%8D%8A%E8%A7%92%E3%82%AB%E3%83%8A%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%3A+%E5%8D%8A%E8%A7%92%EF%BD%B6%EF%BE%85%0A%0A%E5%90%8C%E7%BE%A9%E8%AA%9E%E3%81%AE%E3%81%B0%E3%82%89%E3%81%A4%E3%81%8D%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%3A+%E3%83%86%E3%83%AC%E3%83%93%E3%82%B8%E3%83%A7%E3%83%B3%E3%81%A8%E3%83%86%E3%83%AC%E3%83%93%0A"

[[menu.footer_middle]]
name = "ブログ"
URL = "blog/"

[[menu.footer_middle]]
name = "投げ銭"
URL = "https://github.com/sponsors/hata6502"

# footer menu right
[[menu.footer_right]]
name = "プライバシーポリシー"
URL = "https://github.com/hata6502/kohsei-san#%E3%83%97%E3%83%A9%E3%82%A4%E3%83%90%E3%82%B7%E3%83%BC%E3%83%9D%E3%83%AA%E3%82%B7%E3%83%BC"

[[menu.footer_right]]
name = "免責事項"
URL = "https://github.com/hata6502/kohsei-san#disclaimer"

[[menu.footer_right]]
name = "FAQ"
URL = "https://github.com/hata6502/kohsei-san/discussions"

#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "160px"
# Meta data
description = "その場ですぐに文章を校正できるメモ帳アプリです。オフラインで会員登録不要、スマホアプリとしてもご利用いただけます。"
author = "Tomoyuki Hata"
images = ["images/favicon.png"]
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io

########### footer content ##########
footer_menu_middle = "Contents"
footer_menu_right = "Support"
footer_content = "その場ですぐに文章を校正できるメモ帳アプリです。"
# copyright
copyright = "Copyright (c) [Tomoyuki Hata](https://github.com/hata6502). Released under the [MIT License](https://github.com/hata6502/kohsei-san/blob/master/LICENSE). "

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "使ってみる"
link = "https://kohsei-san.b-hood.site/?text=%E5%86%97%E9%95%B7%E3%81%AA%E8%A1%A8%E7%8F%BE%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%8C%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%80%82%0A%0A%E8%AA%A4%E5%AD%97%E8%84%B1%E5%AD%97%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%97%E3%81%9F%E3%82%8A%E3%80%81%E8%A8%80%E3%81%84%E5%9B%9E%E3%81%97%E3%82%92%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%81%97%E3%81%BE%E3%81%99%E3%80%82%0A%0A%E5%85%A5%E5%8A%9B%E3%83%9F%E3%82%B9%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%3A+%E5%85%A5%E5%8A%9Bm%E3%82%B9%0A%0A%E5%8D%8A%E8%A7%92%E3%82%AB%E3%83%8A%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%3A+%E5%8D%8A%E8%A7%92%EF%BD%B6%EF%BE%85%0A%0A%E5%90%8C%E7%BE%A9%E8%AA%9E%E3%81%AE%E3%81%B0%E3%82%89%E3%81%A4%E3%81%8D%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%3A+%E3%83%86%E3%83%AC%E3%83%93%E3%82%B8%E3%83%A7%E3%83%B3%E3%81%A8%E3%83%86%E3%83%AC%E3%83%93%0A"

  
############################# social site ########################
[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/hata6502"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/hata6502"
